# $Id$

HEADERS = dftplusu.fh

OBJ = dftplusu_hamiltonian.o dftplusu_end.o grad_dftplusu.o dftplusu_init.o
OBJ_OPTIMIZE = 

USES_BLAS =

LIBRARY = libnwdft.a

LIB_INCLUDES = -I../include 
LIB_INCLUDES += -I.


include ../../config/makefile.h
include ../../config/makelib.h
