# $Id$

HEADERS = dftplusu.fh

OBJ = dftplusu_hamiltonian.o dftplusu_end.o
OBJ_OPTIMIZE = dftplusu_init.o

USES_BLAS = 

LIBRARY = libnwdft.a

LIB_INCLUDES = -I../include 
LIB_INCLUDES += -I.


include ../../config/makefile.h
include ../../config/makelib.h
